2024-11-14 14:57:37,116 INFO    MainThread:493470 [wandb_setup.py:_flush():79] Current SDK version is 0.18.5
2024-11-14 14:57:37,117 INFO    MainThread:493470 [wandb_setup.py:_flush():79] Configure stats pid to 493470
2024-11-14 14:57:37,118 INFO    MainThread:493470 [wandb_setup.py:_flush():79] Loading settings from /home/users1/linchi/.config/wandb/settings
2024-11-14 14:57:37,118 INFO    MainThread:493470 [wandb_setup.py:_flush():79] Loading settings from /home/users1/linchi/2024WS-FM/FM_MedVQA/wandb/settings
2024-11-14 14:57:37,119 INFO    MainThread:493470 [wandb_setup.py:_flush():79] Loading settings from environment variables: {}
2024-11-14 14:57:37,120 INFO    MainThread:493470 [wandb_setup.py:_flush():79] Applying setup settings: {'mode': None, '_disable_service': None}
2024-11-14 14:57:37,121 INFO    MainThread:493470 [wandb_setup.py:_flush():79] Inferring run settings from compute environment: {'program_relpath': 'vilt_peft.py', 'program_abspath': '/home/users1/linchi/2024WS-FM/FM_MedVQA/vilt_peft.py', 'program': '/home/users1/linchi/2024WS-FM/FM_MedVQA/vilt_peft.py'}
2024-11-14 14:57:37,121 INFO    MainThread:493470 [wandb_setup.py:_flush():79] Applying login settings: {}
2024-11-14 14:57:37,122 INFO    MainThread:493470 [wandb_init.py:_log_setup():534] Logging user logs to /home/users1/linchi/2024WS-FM/FM_MedVQA/wandb/run-20241114_145737-5a8oavsy/logs/debug.log
2024-11-14 14:57:37,122 INFO    MainThread:493470 [wandb_init.py:_log_setup():535] Logging internal logs to /home/users1/linchi/2024WS-FM/FM_MedVQA/wandb/run-20241114_145737-5a8oavsy/logs/debug-internal.log
2024-11-14 14:57:37,123 INFO    MainThread:493470 [wandb_init.py:init():621] calling init triggers
2024-11-14 14:57:37,124 INFO    MainThread:493470 [wandb_init.py:init():628] wandb.init called with sweep_config: {}
config: {'epochs': 10, 'batch_size': 4, 'learning_rate': 5e-05, 'lora_r': 8, 'lora_alpha': 16, 'lora_dropout': 0.1}
2024-11-14 14:57:37,124 INFO    MainThread:493470 [wandb_init.py:init():671] starting backend
2024-11-14 14:57:37,125 INFO    MainThread:493470 [wandb_init.py:init():675] sending inform_init request
2024-11-14 14:57:37,133 INFO    MainThread:493470 [backend.py:_multiprocessing_setup():104] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2024-11-14 14:57:37,135 INFO    MainThread:493470 [wandb_init.py:init():688] backend started and connected
2024-11-14 14:57:37,152 INFO    MainThread:493470 [wandb_init.py:init():783] updated telemetry
2024-11-14 14:57:37,203 INFO    MainThread:493470 [wandb_init.py:init():816] communicating run to backend with 90.0 second timeout
2024-11-14 14:57:37,436 ERROR   MainThread:493470 [wandb_init.py:init():842] encountered error: failed to upsert bucket: returned error 404 Not Found: {"errors":[{"message":"entity your_entity not found during upsertBucket","path":["upsertBucket"]}],"data":{"upsertBucket":null}}
2024-11-14 14:57:37,436 ERROR   MainThread:493470 [wandb_init.py:init():1266] error in wandb.init()
Traceback (most recent call last):
  File "/home/users1/linchi/2024WS-FM/FM_MedVQA/eepy/med_vqa_py3.9/lib64/python3.9/site-packages/wandb/sdk/wandb_init.py", line 1256, in init
    return wi.init()
  File "/home/users1/linchi/2024WS-FM/FM_MedVQA/eepy/med_vqa_py3.9/lib64/python3.9/site-packages/wandb/sdk/wandb_init.py", line 848, in init
    raise error
wandb.errors.errors.CommError: failed to upsert bucket: returned error 404 Not Found: {"errors":[{"message":"entity your_entity not found during upsertBucket","path":["upsertBucket"]}],"data":{"upsertBucket":null}}
